require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/

Metrics/LineLength:
  Max: 100
  AlowHeredoc: false
  AllowURI: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
