require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/
    - db/schema.rb

Metrics/LineLength:
  Max: 100
  AllowHeredoc: false
  AllowURI: false

Style/AndOr:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
