# frozen_string_literal: true

source "https://rubygems.org"

gem "awrence"
gem "cancancan"
gem "jbuilder"
gem "memoist"
gem "pg"
gem "polist"
gem "puma"
gem "rails"
gem "sequel-rails"
gem "sequel_secure_password"

group :production do
  gem "redis", "~> 3.0"
end

group :development, :test do
  gem "pry-rails"

  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"

  gem "factory_bot_rails"
end

group :development do
end

group :test do
  gem "database_cleaner"
  gem "rspec-rails"
  gem "rubocop"
  gem "rubocop-rspec"
  gem "spring-commands-rspec"
end
