# frozen_string_literal: true

source "https://rubygems.org"

gem "jbuilder"
gem "pg"
gem "puma"
gem "rails"
gem "sequel-rails"

group :production do
  gem "redis", "~> 3.0"
end

group :development, :test do
  gem "pry-rails"

  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"

  gem "factory_bot_rails"
end

group :development do
end

group :test do
  gem "database_cleaner"
  gem "rspec-rails"
  gem "rubocop"
  gem "rubocop-rspec"
  gem "spring-commands-rspec"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
